# Generated by Django 5.2 on 2025-04-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('mpay_code', models.CharField(blank=True, max_length=30, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('IDNP', models.CharField(max_length=13, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('owner_type', models.CharField(choices=[('fizic', 'fizic'), ('juridic', 'juridic')], default='fizic', max_length=10)),
                ('VAT_code', models.CharField(blank=True, max_length=13, null=True)),
                ('region', models.CharField(max_length=50)),
                ('exploitation_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
